from django.urls import include, path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from .serializers import CustomTokenObtainPairSerializer, CustomTokenRefreshSerializer
from .views import (
    DeleteNotificationView,
    AdminDashboardView,
    AdminQuestionDetailView,
    AdminQuestionBulkImportView,
    AdminAnswerImageUploadView,
    AdminQuestionListView,
    AdminAnswerContributionDetailView,
    AdminAnswerContributionListView,
    AdminContributionSubmissionDetailView,
    AdminContributionSubmissionListView,
    AdminCreditPersonListView,
    AdminSemesterListView,
    AdminSemesterDetailView,
    AdminDiscussionDetailView,
    AdminDiscussionListView,
    AdminMockTestDetailView,
    AdminMockTestCsvImportView,
    AdminMockTestListView,
    AdminMockTestQuestionDetailView,
    AdminMockTestQuestionListView,
    AdminNotificationDetailView,
    AdminNotificationListView,
    AdminSubjectBulkImportView,
    AdminSubjectDetailView,
    AdminSubjectNoteListView,
    AdminSubjectNoteCsvImportView,
    AdminSubjectSyllabusView,
    AdminSubjectSyllabusCsvImportView,
    AdminSubjectYearListView,
    AdminSubjectListView,
    AdminNoteDetailView,
    AdminSyllabusUnitDetailView,
    AdminSyllabusUnitListView,
    AdminTestimonialDetailView,
    AdminTestimonialListView,
    AdminUserDetailView,
    AdminUserListView,
    ContactMessageCreateView,
    ContributionSubmissionCreateView,
    ChangePasswordView,
    DeleteAccountView,
    DeviceTokenView,
    EmailSubscriptionCreateView,
    GoogleLoginView,
    LogoutView,
    MarkAllNotificationsReadView,
    MarkNotificationReadView,
    NotificationListView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    ProfileView,
    TestimonialListCreateView,
    UnreadNotificationCountView,
)


class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer


class CustomTokenRefreshView(TokenRefreshView):
    serializer_class = CustomTokenRefreshSerializer


urlpatterns = [
    path('', include('djoser.urls')),
    path('jwt/create/', CustomTokenObtainPairView.as_view()),
    path('jwt/refresh/', CustomTokenRefreshView.as_view()),
    path('jwt/verify/', TokenVerifyView.as_view()),
    path('google/', GoogleLoginView.as_view(), name='google-login'),
    path('password-reset/', PasswordResetRequestView.as_view()),
    path('password-reset/confirm/', PasswordResetConfirmView.as_view()),
    path('password/change/', ChangePasswordView.as_view()),
    path('account/', DeleteAccountView.as_view()),
    path('logout/', LogoutView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('device-tokens/', DeviceTokenView.as_view()),
    path('contact/', ContactMessageCreateView.as_view()),
    path('contributions/', ContributionSubmissionCreateView.as_view()),
    path('email-subscriptions/', EmailSubscriptionCreateView.as_view()),
    path('testimonials/', TestimonialListCreateView.as_view()),
    path('notifications/', NotificationListView.as_view()),
    path('notifications/unread-count/', UnreadNotificationCountView.as_view()),
    path('notifications/mark-all-read/', MarkAllNotificationsReadView.as_view()),
    path('notifications/<int:pk>/read/', MarkNotificationReadView.as_view()),
    path('notifications/<int:pk>/', DeleteNotificationView.as_view()),
    path('admin/dashboard/', AdminDashboardView.as_view()),
    path('admin/semesters/', AdminSemesterListView.as_view()),
    path('admin/semesters/<int:pk>/', AdminSemesterDetailView.as_view()),
    path('admin/subjects/', AdminSubjectListView.as_view()),
    path('admin/subjects/bulk-import/', AdminSubjectBulkImportView.as_view()),
    path('admin/subjects/<int:pk>/', AdminSubjectDetailView.as_view()),
    path('admin/subjects/<int:pk>/syllabus/', AdminSubjectSyllabusView.as_view()),
    path('admin/subjects/<int:pk>/syllabus/import-csv/', AdminSubjectSyllabusCsvImportView.as_view()),
    path('admin/subjects/<int:pk>/syllabus/units/', AdminSyllabusUnitListView.as_view()),
    path('admin/syllabus-units/<int:pk>/', AdminSyllabusUnitDetailView.as_view()),
    path('admin/credit-people/', AdminCreditPersonListView.as_view()),
    path('admin/subjects/<int:pk>/notes/', AdminSubjectNoteListView.as_view()),
    path('admin/subjects/<int:pk>/notes/import-csv/', AdminSubjectNoteCsvImportView.as_view()),
    path('admin/notes/<int:pk>/', AdminNoteDetailView.as_view()),
    path('admin/subjects/<int:pk>/years/', AdminSubjectYearListView.as_view()),
    path('admin/questions/', AdminQuestionListView.as_view()),
    path('admin/questions/bulk-import/', AdminQuestionBulkImportView.as_view()),
    path('admin/answer-images/', AdminAnswerImageUploadView.as_view()),
    path('admin/questions/<int:pk>/', AdminQuestionDetailView.as_view()),
    path('admin/answer-contributions/', AdminAnswerContributionListView.as_view()),
    path('admin/answer-contributions/<int:pk>/', AdminAnswerContributionDetailView.as_view()),
    path('admin/contributions/', AdminContributionSubmissionListView.as_view()),
    path('admin/contributions/<int:pk>/', AdminContributionSubmissionDetailView.as_view()),
    path('admin/users/', AdminUserListView.as_view()),
    path('admin/users/<int:pk>/', AdminUserDetailView.as_view()),
    path('admin/discussions/', AdminDiscussionListView.as_view()),
    path('admin/discussions/<int:pk>/', AdminDiscussionDetailView.as_view()),
    path('admin/testimonials/', AdminTestimonialListView.as_view()),
    path('admin/testimonials/<int:pk>/', AdminTestimonialDetailView.as_view()),
    path('admin/notifications/', AdminNotificationListView.as_view()),
    path('admin/notifications/<int:pk>/', AdminNotificationDetailView.as_view()),
    path('admin/mock-tests/', AdminMockTestListView.as_view()),
    path('admin/mock-tests/import-csv/', AdminMockTestCsvImportView.as_view()),
    path('admin/mock-tests/<int:pk>/', AdminMockTestDetailView.as_view()),
    path('admin/mock-tests/<int:pk>/questions/', AdminMockTestQuestionListView.as_view()),
    path('admin/mock-test-questions/<int:pk>/', AdminMockTestQuestionDetailView.as_view()),
]
