from django.urls import path
from .views import (
    DiscussionDetailView,
    DiscussionReplyView,
    MockTestDetailView,
    MockTestResultDetailView,
    MockTestSessionStartView,
    PlatformDiscussionListView,
    SearchView,
    SemesterListView,
    SemesterSubjectListView,
    SubjectDetailView,
    SubjectDiscussionListView,
    SubjectMockTestListView,
    SubjectNoteDetailView,
    SubjectNoteListView,
    SubjectSyllabusView,
    SubjectYearListView,
    SubmitMockTestView,
    UserMockTestResultListView,
    QuestionContributionListView,
    YearQuestionListView,
    YearQuestionPaperView,
)

urlpatterns = [
    path('semesters/', SemesterListView.as_view()),
    path('semesters/<slug:semester_slug>/subjects/', SemesterSubjectListView.as_view()),
    path('subjects/<slug:subject_slug>/', SubjectDetailView.as_view()),
    path('subjects/<slug:subject_slug>/syllabus/', SubjectSyllabusView.as_view()),
    path('subjects/<slug:subject_slug>/notes/', SubjectNoteListView.as_view()),
    path('subjects/<slug:subject_slug>/notes/<slug:note_slug>/', SubjectNoteDetailView.as_view()),
    path('subjects/<slug:subject_slug>/years/', SubjectYearListView.as_view()),
    path('subjects/<slug:subject_slug>/questions/<str:year>/', YearQuestionListView.as_view()),
    path('questions/<int:pk>/contributions/', QuestionContributionListView.as_view()),
    path('subjects/<slug:subject_slug>/papers/<str:year>/', YearQuestionPaperView.as_view()),
    path('subjects/<slug:subject_slug>/mock-tests/', SubjectMockTestListView.as_view()),
    path('mock-tests/<int:pk>/', MockTestDetailView.as_view()),
    path('mock-tests/<int:pk>/sessions/', MockTestSessionStartView.as_view()),
    path('mock-tests/<int:pk>/submit/', SubmitMockTestView.as_view()),
    path('mock-tests/results/', UserMockTestResultListView.as_view()),
    path('mock-tests/results/<int:pk>/', MockTestResultDetailView.as_view()),
    path('discussions/', PlatformDiscussionListView.as_view()),
    path('subjects/<slug:subject_slug>/discussions/', SubjectDiscussionListView.as_view()),
    path('discussions/<int:pk>/', DiscussionDetailView.as_view()),
    path('discussions/<int:pk>/replies/', DiscussionReplyView.as_view()),
    path('discussion-replies/<int:pk>/', DiscussionReplyView.as_view()),
    path('search/', SearchView.as_view()),
]
