# Generated by Django 6.0 on 2026-05-05 10:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('accounts', 'SubscriptionPlan')
    plans = [
        {
            'name': 'Monthly',
            'slug': 'monthly',
            'price': Decimal('150.00'),
            'billing_period': 'monthly',
            'duration_days': 30,
            'description': 'Monthly access to premium answers and papers.',
            'features': [
                'Unlock detailed answers',
                'Download premium question papers',
                'Access all available semesters',
            ],
            'sort_order': 1,
        },
        {
            'name': 'Quarterly',
            'slug': 'quarterly',
            'price': Decimal('500.00'),
            'billing_period': 'quarterly',
            'duration_days': 90,
            'description': 'Three months of premium access.',
            'features': [
                'Everything in Monthly',
                'Better value for a full exam cycle',
                'Access all available semesters',
            ],
            'sort_order': 2,
        },
        {
            'name': 'Yearly',
            'slug': 'yearly',
            'price': Decimal('900.00'),
            'billing_period': 'yearly',
            'duration_days': 365,
            'description': 'One year of premium access.',
            'features': [
                'Everything in Quarterly',
                'Best value for regular preparation',
                'Access all future updates during the year',
            ],
            'sort_order': 3,
        },
    ]

    for plan in plans:
        SubscriptionPlan.objects.update_or_create(
            slug=plan['slug'],
            defaults=plan,
        )


def remove_seeded_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('accounts', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(
        slug__in=['monthly', 'quarterly', 'yearly'],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.RunPython(
            seed_subscription_plans,
            remove_seeded_subscription_plans,
        ),
    ]
