# Generated by Django 6.0 on 2026-05-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_bio_customuser_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
