# Generated by Codex on 2026-05-21

from django.db import migrations, models


def backfill_inactive_users(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(is_active=False).update(account_status='blocked')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(
                choices=[
                    ('active', 'Active'),
                    ('suspended', 'Suspended'),
                    ('blocked', 'Blocked'),
                ],
                default='active',
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_inactive_users, migrations.RunPython.noop),
    ]
