# Generated by Django 6.0 on 2026-05-21 11:26

from django.db import migrations, models


def keep_latest_testimonial_per_user(apps, schema_editor):
    Testimonial = apps.get_model('accounts', 'Testimonial')
    duplicates = (
        Testimonial.objects
        .exclude(user_id=None)
        .values_list('user_id', flat=True)
        .distinct()
    )

    for user_id in duplicates:
        ids = list(
            Testimonial.objects
            .filter(user_id=user_id)
            .order_by('-updated_at', '-created_at', '-id')
            .values_list('id', flat=True)
        )
        if len(ids) > 1:
            Testimonial.objects.filter(id__in=ids[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_suspended_until'),
    ]

    operations = [
        migrations.RunPython(
            keep_latest_testimonial_per_user,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_testimonial_per_user'),
        ),
    ]
