# Generated by Django 6.0 on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_testimonial_unique_testimonial_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(
                choices=[
                    ('reply', 'Discussion Reply'),
                    ('paper', 'New Question Paper'),
                    ('mock_test', 'New Mock Test'),
                    ('custom', 'Custom'),
                ],
                max_length=20,
            ),
        ),
    ]
