# Generated by Django 6.0.2 on 2026-05-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reply', 'Discussion Reply'), ('paper', 'New Question Paper'), ('mock_test', 'New Mock Test'), ('contribution', 'Answer Contribution'), ('custom', 'Custom')], max_length=20),
        ),
    ]
