# Generated by Django 6.0 on 2026-05-06 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['section__order', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='year',
            name='course_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='year',
            name='full_marks',
            field=models.CharField(default='60', max_length=40),
        ),
        migrations.AddField(
            model_name='year',
            name='institute',
            field=models.CharField(default='Institute of Science and Technology', max_length=160),
        ),
        migrations.AddField(
            model_name='year',
            name='institution',
            field=models.CharField(default='Tribhuvan University', max_length=120),
        ),
        migrations.AddField(
            model_name='year',
            name='instructions',
            field=models.TextField(blank=True, default='Candidates are required to give their answers in their own words as far as practicable.\nThe figures in the margin indicate full marks.'),
        ),
        migrations.AddField(
            model_name='year',
            name='level',
            field=models.CharField(default='Bachelor Level / Science', max_length=160),
        ),
        migrations.AddField(
            model_name='year',
            name='pass_marks',
            field=models.CharField(default='24', max_length=40),
        ),
        migrations.AddField(
            model_name='year',
            name='time',
            field=models.CharField(default='3 Hours', max_length=40),
        ),
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('instruction', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.year')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='academics.questionsection'),
        ),
    ]
