# Generated by Django 6.0.2 on 2026-03-30 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_discussion_discussionreply_mocktest_mocktestquestion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='discussionreply',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='discussionreply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='academics.discussionreply'),
        ),
    ]
