# Generated by Django 6.0 on 2026-05-07 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_discussion_discussionreply_mocktest_mocktestquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1)),
                ('correct_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='academics.mocktestquestion')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academics.mocktestresult')),
            ],
            options={
                'unique_together': {('result', 'question')},
            },
        ),
    ]
