# Generated by Django 6.0 on 2026-05-22 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_answercontribution_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='course_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='course_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='course_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='course_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='credit_hours',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='full_marks',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='laboratory_work',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='nature',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='pass_marks',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='reference_books',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='semester_label',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='text_books',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='syllabus/'),
        ),
        migrations.CreateModel(
            name='SyllabusUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=40)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.syllabus')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('syllabus', 'slug')},
            },
        ),
    ]
