# Generated by Django 6.0 on 2026-05-22 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.syllabus')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
