# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_syllabussection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
