# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_note_pdf_file_alter_note_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='credit_image',
            field=models.ImageField(blank=True, null=True, upload_to='notes/credits/'),
        ),
        migrations.AddField(
            model_name='note',
            name='credit_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='note',
            name='credit_url',
            field=models.URLField(blank=True),
        ),
    ]
