# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_note_credit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_image_paths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='source_question_id',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='question',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(
                condition=~models.Q(source_question_id=''),
                fields=('source_question_id',),
                name='unique_question_source_question_id',
            ),
        ),
    ]
