# Generated by Django 6.0.2 on 2026-05-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_note_credit_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercontribution',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
