# Generated by Django 6.0.2 on 2026-05-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_answercontribution_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercontribution',
            name='is_main_answer',
            field=models.BooleanField(default=False),
        ),
    ]
